knp_paginator:
    page_range: 5
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
